services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8080:80" # Maps port 80 on the container to 8080 on the host
    env_file:
      - ./env/wordpress.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpressdb

  wordpressdb:
    image: mysql
    restart: always
    ports:
      - "3306:3306"

    env_file:
      - ./env/mysql.env
    volumes:
      - wordpressdb:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  wordpress:
  wordpressdb:
