services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./env/wordpress.env
      
    volumes:
      - wordpress:/var/www/html

  wordpressdb:
    image: mysql
    restart: always
    env_file:
      - ./env/mysql.env
     
    volumes:
      - wordpressdb:/var/lib/mysql

volumes:
  wordpress:
  wordpressdb:
